services:

  nginx:
    image: nginx:alpine
    container_name: proxy_nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app-backend:
      conditions:
         - service_healthy
         
    networks:
      - red-cba




  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd
    restart: always

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - red-cba

  app-backend:
    image: wscanga/app-backend:v2
    container_name: app-backend
    restart: always
    build: .

    depends_on:
      - servidor-bd:
        condition:
          - service_healthy

    env_file:
      - .env

    ports:
      - "${FLASK_PORT}:5050"

    volumes:
      - .:/home/myapp

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s


    networks:
      - red-cba

networks:
  red-cba:
    driver: bridge

volumes:
  mysql-data: